INSERT INTO CarUsers (FirstName, LastName, UserName, Password, AccountType) VALUES ('Jim', 'Yount', 'jay', 'MyPa55', 3);
INSERT INTO CarUsers (FirstName, LastName, UserName, Password, AccountType) VALUES ('Buddy', 'Guy', 'bud', 'MyPa55', 2);
INSERT INTO CarUsers (FirstName, LastName, UserName, Password, AccountType) VALUES ('Hey', 'Jude', 'jude', 'MyPa55', 1);
INSERT INTO CarUsers (FirstName, LastName, UserName, Password, AccountType) VALUES ('Humphrey', 'Bogart', 'Maltese', 'Classic', 2);
INSERT INTO CarUsers (FirstName, LastName, UserName, Password, AccountType) VALUES ('Boba', 'Fett', 'Hunter1', 'Bounty', 1);

INSERT INTO Cars (Price, Make, Model, Color, Year) VALUES ('5000', 'Honda', 'Civic', 'Red', '2005');
INSERT INTO Cars (Price, Make, Model, Color, Year, OwnerID, PayMonths, BoughtYear, BoughtMonth) VALUES ('6000', 'Toyota', 'Corolla S', 'Silver', '2003', 3, 32, 2009, 10);
INSERT INTO Cars (Price, Make, Model, Color, Year, OwnerID, PayMonths, BoughtYear, BoughtMonth) VALUES ('8992', 'Chevrolet', 'Corvette', 'Red', '2013', 5, 64, 2018, 6);
INSERT INTO Cars (Price, Make, Model, Color, Year) VALUES ('3500', 'Lincoln', 'Continental', 'Black', '2007');
INSERT INTO Cars (Price, Make, Model, Color, Year) VALUES ('4000', 'Ford', 'Taurus', 'White', '2011');
INSERT INTO Cars (Price, Make, Model, Color, Year) VALUES ('5500', 'Hyundai', 'Sonata', 'Silver', '2008');

INSERT INTO Offers (OfferCarID, OfferCarUserID, Offer) VALUES (4, 2, 3000);
INSERT INTO Offers (OfferCarID, OfferCarUserID, Offer) VALUES (4, 4, 3500);

INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (3, 187.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);
INSERT INTO Payments (PayerID, PaidAmount) VALUES (5, 140.5);

commit;
exit;